INSERT INTO Trip_Flight_Activity_Fact (
    fact_key,
    ticket_number,
    passenger_key,
    passenger_profile_key,
    departure_airport_key,
    arrival_airport_key,
    booking_channel_key,
    flight_type_key,
    scheduled_departure_date_key,
    actual_departure_date_key,
    scheduled_arrival_date_key,
    actual_arrival_date_key,
    total_segments,
    total_fare_price,
    total_taxes,
    total_overweight_luggage,
    total_upgrade_fees,
    total_net_price,
    total_cost,
    total_profit,
    total_overnight_stays
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY s.ticket_number) AS fact_key,
    s.ticket_number,
    s.passenger_key,
    s.passenger_profile_key,
    s.departure_airport_key,
    s.arrival_airport_key,
    s.booking_channel_key,
    s.flight_type_key,
    s.scheduled_departure_date_key,
    s.actual_departure_date_key,
    s.scheduled_arrival_date_key,
    s.actual_arrival_date_key,
    COUNT(*) AS total_segments,
    SUM(s.fare_price) AS total_fare_price,
    SUM(s.taxes) AS total_taxes,
    SUM(s.overweight_luggage) AS total_overweight_luggage,
    SUM(s.upgrade_fees) AS total_upgrade_fees,
    SUM(s.net_price) AS total_net_price,
    SUM(s.cost) AS total_cost,
    SUM(s.profit) AS total_profit,
    -- Generate a random number between 0 and 10 for total overnight stays
    FLOOR(DBMS_RANDOM.VALUE(0, 11)) AS total_overnight_stays
FROM 
    Segment_Flight_Activity_Fact s
GROUP BY 
    s.ticket_number,
    s.passenger_key,
    s.passenger_profile_key,
    s.departure_airport_key,
    s.arrival_airport_key,
    s.booking_channel_key,
    s.flight_type_key,
    s.scheduled_departure_date_key,
    s.actual_departure_date_key,
    s.scheduled_arrival_date_key,
    s.actual_arrival_date_key;
